baseURL: "/"
languageCode: "en-us"
title: "ThachPham"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 6
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blogs
      weight: 1
    - identifier: gallery
      name: Gallery
      title: Blog posts
      url: /gallery
      weight: 2
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "ThachPham"
  description: Text about my cool site
  # staticPath: ""  # The path to serve the static files from
  favicon: "/fav.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    # defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "ThachPham" # Brand name for the brand | default is the title variable
    disableSearch: false
    # searchPlaceholder: "Search"
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Phạm Thạch"
    subtitle: "I am a DevOps engineer"
    content: |-
      My area of expertise is cloud computing, and I hold two AWS certifications.

      This website utilizes the hugo-profile template, which is built on gohugo, and employs Git Actions for the build process.
    image: /images/pic2.jpg
    bottomImage:
      enable: true  # 16 dấu cộng bên trái phía dưới, không biết để làm gì
    # roundImage: true # Make hero image circular | default false
    button:
      enable: true
      name: "Resume"
      url: "#"
      download: true
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/thachpham2k
        - icon: fab fa-facebook
          url: https://www.facebook.com/thach.pham.dev/
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/phamthach/
      customIcons:
        - icon: /images/tryhackme.png
          url: "https://tryhackme.com/p/ishimaru"

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/pic1.jpg"
    content: |-
      As a DevOps Engineer with a keen interest in AWS Cloud technologies, I have a background in Linux, networking, and cyber security, and a strong passion for the convergence of solution and technology, as well as the automation of tasks.

      I have practical experience in applying SOLID, OOP, Spring boot framework to develop microservices running on AWS. Additionally, I can also construct a devops pipeline using Jenkin and AWS services.

      Currently, I am employed as a Cloud Engineer at CMC Global (https://cmcglobal.com.vn) in Vietnam. 
      
      Additionally, I hold the role of an admin in the VAUG | Viet-AWS University Group (https://www.facebook.com/groups/vaugvn).
    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "Java"
        - "AWS"
        - "Python"
        - "CI/CD"
        - "C/C++"
        - "Kubernetes"

  # Experience
  experience:
    enable: true
    # title: "Custom Name"
    items:
      - job: "Cloud Engineer"
        company: "CMC Global"
        companyUrl: "https://cmcglobal.com.vn"
        date: "Oct 2022 - present"
        # featuredLink:
        #   enable: true
        #   url: "#"
        # info:
        #   enable: true
        #   content: I worked as a software developer for more than one year in CMC Global.
        content: |
          I work as a Cloud Engineer at CMC Global in Vietnam.

          In here, I am:
            - Working with Java Spring framework
            - Implementing CI/CD using CodePipeline, Jenkins
            - Infrastructure as Code (IaC) with Terraform, CloudFormation, SAM
            - Deploying infrastructure on AWS
            - Designing infrastructure and calculating cost
            - Creating proof of concept for systems

      - job: "Intern Cloud Engineer"
        company: "CMC Telecom"
        companyUrl: "https://cmctelecom.vn"
        date: "Jun 2022 - Sep 2022"
        # featuredLink:
        #   enable: true
        #   name: "View the project"
        #   url: "#"
        content: |-
          I work as a Cloud Engineer at CMC Telecom in Vietnam. 
          In here, I am:
            - Learn about AWS cloud and take AWS certificate exam 
            - Learn about terraform and using it to build infrastructure as code 
            - Work with scum model 
            - Draw the infrastructure and calculate the cost 

  # Education
  education:
    enable: false
    # title: "Custom Name"
    index: false
    items:
      - title: "Information Security"
        school:
          name: "Posts and Telecommunications Institute of Technology Ho Chi Minh Branch"
          url: "https://ptithcm.edu.vn/"
        date: "2018 - 2023"
        # GPA: "3.8 out of 5.0"
        content: |-
          Extracurricular Activities
            - Lorem ipsum dolor sit amet consectetur adipisicing elit. 
            - Tempora esse, eaque delectus nulla quo doloribus itaque expedita alias natus optio totam maxime nihil excepturi velit a animi laborum hic similique.
        # featuredLink:
        #   enable: true
        #   name: "My academic record"
        #   url: "https://example.com"

  # Achievements
  achievements:
    enable: true
    # title: "Custom Name"
    items:
      - title: AWS Solution Architect - Associate Certificate
        content: I pass AWS Solution Architect - Associate Certificate exam.
        url: https://www.credly.com/badges/249858da-315f-4da4-a93f-2907d01a9dff/public_url
      - title: AWS Developer - Associate Certificate
        content: I pass AWS Developer - Associate Certificate exam.
        url: https://www.credly.com/badges/9a9f4359-c470-49cc-b2ca-5b335b36af0d/public_url

  # projects
  projects:
    enable: false
    # title: "Custom Name"
    items:
      - title: Lorem ipsum
        content: Lorem ipsum dolor sit amet consectetur adipisicing elit. 
        image: /images/profile.png
        # featured:
        #   name: Demo
        #   link: "#"
        badges:
          - "Java"
        links:
          - icon: fa fa-envelope
            url: 
          - icon: fab fa-github
            url: https://github.com/thachpham2k
          - icon: fab fa-facebook
            url: https://www.facebook.com/thach.pham.dev

      - title: Image Converter
        content: A web app to convert image to pdf, png to jpg, png to jpg and png to webp without database using django.
        image: /images/projects/converter.jpg
        # featured:
        #   name: Demo
        #   link: https://django-converter.herokuapp.com
        badges:
          - "Django"
          - "Bootstrap"
        links:
          - icon: fab fa-github
            url: https://github.com/gurusabarish/converter

  #Contact
  contact:
    enable: true
    # title: "Custom Name"
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    email: phamthach2506@gmail.com
    btnName: Mail me
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"

  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: Recent Posts
      enable: true
      disableFeaturedImage: false
    socialNetworks:
      github: https://github.com/thachpham2k
      linkedin: https://www.linkedin.com/in/phamthach/
      instagram: https://www.instagram.com/_thach.pham/
      facebook: https://www.facebook.com/thach.pham.dev/

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"
